Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 22, host: 12202
  config.vm.network "private_network", ip:"192.168.33.2"
  config.vm.network "private_network", ip:"10.0.2.100", auto_conf: false
  # リポジトリをJAISTのミラーサーバに変更
  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i'~' -E "s@http://(..\.)?(archive|security)\.ubuntu\.com/ubuntu@http://ftp.jaist.ac.jp/pub/Linux/ubuntu@g" /etc/apt/sources.list
  SHELL
end
