Vagrant.configure("2") do |config|
  config.vm.box = "higebu/vyos-1.1.7-amd64"

  config.vm.define :node1 do |node|
    node.vm.network :forwarded_port, guest: 22, host: 12204

    # Management
    node.vm.network "private_network", ip: "192.168.33.101"

    node.vm.network "private_network", ip: "192.168.1.100", auto_config: false
    node.vm.network "private_network", ip: "10.1.0.101", auto_config: false
  end

  config.vm.define :node2 do |node|
    node.vm.network :forwarded_port, guest: 22, host: 12203

    # Management 
    node.vm.network "private_network", ip: "192.168.33.102"

    node.vm.network "private_network", ip: "192.168.2.100", auto_config: false
    node.vm.network "private_network", ip: "10.1.0.102", auto_config: false

    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus" ,"2", "--ioapic", "on"]
    end
  end

  config.vm.define :node3 do |node|
    node.vm.network :forwarded_port, guest: 22, host: 12206

    # Management
    node.vm.network "private_network", ip: "192.168.33.103"

    node.vm.network "private_network", ip: "192.168.3.100", auto_config: false
    node.vm.network "private_network", ip: "10.1.0.103", auto_config: false
  end

  config.vm.define :node4 do |node|
    node.vm.network :forwarded_port, guest: 22, host: 12207

    # Management 
    node.vm.network "private_network", ip: "192.168.33.104"

    node.vm.network "private_network", ip: "192.168.4.100", auto_config: false
    node.vm.network "private_network", ip: "10.1.0.104", auto_config: false
  end
end